const GET_CURRENT_LOCATION = 'GET_CURRENT_LOCATION';
const GET_CURRENT_LOCATION_SUCCESS = 'GET_CURRENT_LOCATION_SUCCESS';
const GET_LOCATION_INPUT = 'GET_LOCATION_INPUT';
const GET_ADDRESS_PREDICTIONS = 'GET_ADDRESS_PREDICTIONS';
const GET_ADDRESS_PREDICTIONS_SUCCESS = 'GET_ADDRESS_PREDICTIONS_SUCCESS';

export {
  GET_CURRENT_LOCATION,
  GET_CURRENT_LOCATION_SUCCESS,
  GET_LOCATION_INPUT,
  GET_ADDRESS_PREDICTIONS,
  GET_ADDRESS_PREDICTIONS_SUCCESS,
};
